title: RAON Whitehat
author: Core Research Team
email: hbji@raoncorp.com
description: RAON Whitehat Core Research Team Blog
show_excerpts: true
sass:
  sass_dir: _sass
plainwhite:
  name: RAON Whitehat
  tagline: Core Research Team
  date_format: '%b %-d, %Y'
  sitemap: true
  social_links:
    theme: plainwhite
    plugins:
      - jekyll-seo-tag
    remote_theme: thelehhman/plainwhite-jekyll
permalink: /:categories/:title:output_ext